[Interface]
Address = 10.10.10.1/24
PrivateKey = YMfK9dyiXUT8ldabK8lggNPNGoBU8Wm3PQ0JBy4fnEo=
ListenPort = 51820

[Peer]
PublicKey = I0cCgCestvmYhfLdN2JWNlCMrWAOX9aHWQ0W1hRPdnk=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
