#remote 端 
[Interface]
Address = 10.10.12.2/24
PrivateKey = <remote 私钥（请从 remote.key 中获取）>
ListenPort = 51820

[Peer]
PublicKey = KYBO0+1l+KwAg9FsqdO9moc+vch4mpB6oMu4bnC0RF0=
Endpoint = 10.100.0.1:59231
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25