[Interface]
# 客户端私钥
PrivateKey = IERemote客户端私钥内容
Address = 10.10.10.2/24
SaveConfig = true

[Peer]
# FW服务端公钥
PublicKey = 3AsMtjaNQQMf4GpXEm8w/AHuvpm616RAZa9E61XeeDic=
# 服务端公网地址+监听端口
Endpoint = 203.0.113.1:38887
# 允许访问VPN本网段与后端DMZ网段
AllowedIPs = 10.10.10.0/24,10.40.0.0/24
PersistentKeepalive = 25
