[Interface]
# 服务端私钥，我的公钥：3AsMtjaNQQMf4GpXEm8w/AHuvpm616RAZa9E61XeeDic=
PrivateKey = IEFW服务端私钥内容
Address = 10.10.10.1/24
ListenPort = 38887
# 日志与转发配置
SaveConfig = true

[Peer]
# remote客户端公钥
PublicKey = G2ey5MeGX1p9/CYPxE6boxjSu5ejzFFtO1tNgkma2Vs=
# 完整放行VPN网段+DMZ网段
AllowedIPs = 10.10.10.2/32,10.40.0.0/24
PersistentKeepalive = 25
