[Interface]
PrivateKey = 4L4InW+0Qcbbsg7CpAJhd9fq8AwwgBySdIUKAIQ7Glk=
Address = 10.10.10.2/24

[Peer]
# fw服务端公钥
PublicKey = lLbHR5HafinvQckPRTiYNl2Fn0+tgyBO5iXlcV4iemk=
# 防火墙外网地址+wg端口
Endpoint = 203.0.113.1:51820
# 所有内网网段全部走VPN隧道
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
# 保持保活，虚拟机环境防断连
PersistentKeepalive = 25