[Interface]
Address = 10.10.10.1/24
PrivateKey = sO4gK7dns753n286acVKK48FCFVtjYuhOVHVFvtGbWI=
ListenPort = 51820

[Peer]
PublicKey = 8X/7uDlicPqRn6f9LOhiFqccq//7s6YBZ3wJSoCkXl0=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
