[Interface]
Address = 10.10.10.2/24
PrivateKey = WMmKrZnKTC48il4KZtGz4aQWqO39C2o3TaK94EJttWs=

[Peer]
PublicKey = g5r4mRROo9PDE8tWsZ0w06/8zhYr9HpWIRtYxISP8QA=
Endpoint = 192.168.100.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25
