[Interface]
Address = 10.10.10.1/24
PrivateKey = iF0/LVtktehY9HEFQCXDuD5qoawGcr7Nsj+tQAu3EHU=
ListenPort = 51820

[Peer]
PublicKey = uKBEmCPUiGQYV3i8YxpJ41l4XEkwSUrKdBnPKP0ooB4=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
