[Interface]
Address = 172.16.100.2/24
PrivateKey = sB2sCTahyoaQiZqwYkd/HUtZ5SaV3SEYBNtEaO9u22g=

[Peer]
PublicKey = RqQg8wkYwAUeyVyBkUJlZA981gcvqgvDAIyOC0DcPyI=
Endpoint = 10.10.10.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25