[Interface]
Address = 172.16.100.1/24
PrivateKey = KM9rdggKsOArY30h2kEqZLWJveKZzBEqPP0rh5jM/X0=
ListenPort = 51820

[Peer]
PublicKey = iqSNLnhBHhiGcPmvY5bEjSyYDehK19eb+iLbVfvajAU=
AllowedIPs = 172.16.100.2/32
PersistentKeepalive = 25