[Interface]
Address = 10.10.10.2/24
PrivateKey = WJ/9MvWSAS7VTZHTw46FcwIinlqLs+e5uM9Qh1yI+Wg=

[Peer]
PublicKey = n0gexDvYCCqPSuy798b4e0JUNl4V0b7v8CWlVTBoUj4=
Endpoint = 10.10.10.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25