[Interface]
Address = 10.10.10.1/24
PrivateKey = QLUbXPUzJweVdKwbF0iQU3FcLKnqshIFYB70+3ENd0Y=
ListenPort = 51820

[Peer]
PublicKey = rl8fOn3TLUyTAHI3rBcYT3hRA+RebGXzzy+2zaUS/Rs=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25