[Interface]
PrivateKey = gL8u03nDtRb7RUMRh0El0i/JcBol6jgpHmKh59dfjlg=
Address = 10.10.10.1/24
ListenPort = 51820

[Peer]
PublicKey = kjl9EjQ2PbSd1w5Yrjn0yx50xnJ5v1F3DstLKll7g0w=
AllowedIPs = 10.10.10.2/32
