[Interface]
PrivateKey = sLGriSZVN82kA9jXjBuzRDDlo+PSym6RdH90u0LabGw=
Address = 10.10.10.2/24

[Peer]
PublicKey = qzvgOqYmZSt55QjBekjlXRNQJCnwibEzVDpVAEM47io=
Endpoint = 203.0.113.1:51820
AllowedIPs = 10.20.0.0/24, 10.40.0.0/24
PersistentKeepalive = 25
