[Interface]
Address = 10.10.10.3/24
PrivateKey = IHifBFZiUXkOU801Nf9a6tSlXnkmjc4YrLT+7ZFR1Ww=

[Peer]
PublicKey = eNF0bgsPv19aY9nrv0cP7PTBGB/qgw8bJp5RnUF8gxk=
Endpoint = 10.10.10.1:51820
AllowedIPs = 10.10.10.1/32,10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25
