[Interface]
Address = 10.10.10.4/24
PrivateKey = wD8M4E+M01JCKqJoMhDiqbnNq9551VFKOKtsF4282U0=
ListenPort = 51820

[Peer]
PublicKey = nAf7kVh8pDHy3VxZMZoP3Enr84ACZ5k7/XDTY1RVxDY=
AllowedIPs = 10.10.10.3/32
PersistentKeepalive = 25
