[Interface]
Address = 10.10.10.2/24
PrivateKey = EITDCGJQ/tb0qgkD+zLdnZ11mGW40p3Hq920sr/zgXQ=

[Peer]
PublicKey = HKsphKg3Y5qtaDWbPJb8/4euwJxqY4PK7eVpuJ05m0s=
Endpoint = 10.10.10.1:51820
AllowedIPs = 10.20.0.0/24, 10.40.0.0/24
PersistentKeepalive = 25
