[Interface]
Address = 10.10.10.1/24
PrivateKey = MCztgK5LMfXqUUKa0Ur6A8ztAgUOIZPACmNIv5hc61E=
ListenPort = 51820

[Peer]
PublicKey = xTjWD/7nDMFNZtvje7qSXAYX6peUkvHkANUBek6QmUQ=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
