[Interface]
Address = 10.10.10.1/24
PrivateKey = IprjvdHe93draqCLCLienDpykJ/mCGDiSnkwlBKMvUg=
ListenPort = 51820

[Peer]
PublicKey = dfKVw4Chg6046B0HZKMMxTfSN/1NimrKBksqaadyWjY=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25