[Interface]
Address = 10.10.10.2/24
PrivateKey = 6FbwFyBUkRYiV30nrdNsR3pjnoQtsSW61/BxTbNpVUQ=

[Peer]
PublicKey = IprjvdHe93draqCLCLienDpykJ/mCGDiSnkwlBKMvUg=
Endpoint = 203.0.113.254:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25