[Interface]
PrivateKey = +EZAN81bD5yjTC0xHvqBSLpj6bmc4vrs+SVuFGbLsFM=
Address = 10.10.10.1/24
ListenPort = 51820
# 开启IP转发，允许隧道流量转发内网
PostUp = sysctl -w net.ipv4.ip_forward=1
# 关闭时无额外清理
PostDown = true

[Peer]
# remote客户端公钥
PublicKey = 07L1Fx7194p6/12/MCtdLuDmY6+m5rSCE/Hx+RzJsmU=
# 客户端隧道固定IP，仅允许10.10.10.2接入
AllowedIPs = 10.10.10.2/32