[Interface]
Address = 10.10.10.2/24
PrivateKey = 4B8EUSqpkkuF+AGHQvhbGEOcTAtXnRM1dSFdGCYKz1o=
MTU = 1280

[Peer]
PublicKey = FH0CA8+4j9LLW2YaTE1BDgRm4Q4ZdGa9pBTDixBFujc=
Endpoint = 203.0.113.1:51820
AllowedIPs = 10.10.10.0/24,10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25
