[Interface]
Address = 10.10.10.1/24
PrivateKey = 2EayqHDCvzf8919BEoTCP3K7bkDOAw2o/eC9GNb4YWk=
ListenPort = 51820
MTU = 1280

[Peer]
PublicKey = 2U854ZvNhFEhVMbEd3Js7yh0e3oFp4Ahmw5IkKpCsgQ=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
