[Interface]
PrivateKey = WH6GzsCCUSBPIT7XvI9VNY8XJVkXQH8khUQKqRYMSBFM=
Address = 10.10.10.1/24
ListenPort = 51820

[Peer]
PublicKey = /LQ6t2Td1CAuW3lTQuwVGqlluogW6OF6m+CR19tM+kc=
AllowedIPs = 10.10.10.2/32
