[Interface]
PrivateKey = UFZlxZNWUfcBLrHYg/dq8vP9OmBGFL5zQQsrSqgyxkGA=
Address = 10.10.10.2/24

[Peer]
PublicKey = yymjHYyCYZ2qOTagiFZdGTrZ3e/Bb6BdkCK5eEJTWA=
Endpoint = 192.0.2.1:51820
AllowedIPs = 10.20.0.0/24, 10.40.0.0/24, 10.10.10.0/24
PersistentKeepalive = 25
