[Interface]
PrivateKey = SIsuF+eCjoRf/tlUaY+h3YmESzQnzwdAoq9PVeLzq20=
Address = 10.10.10.1/24
ListenPort = 51820

[Peer]
PublicKey = 6nrES6DWOfCTPM67eP82TRXdsxGGoq7LwMQcPWh/m34=
AllowedIPs = 10.10.10.2/32
