# remote客户端WireGuard配置（文档别名vpn-remote.conf）
[Interface]
Address = 10.10.10.2/24
PrivateKey = QGVbBb0JImcYoUpEnThZI/I9MiomLT0N5JOFrzxkhnc=

[Peer]
PublicKey = 5Hjh6/V4uYAoQmtpiAzN6c811RXmO0lsdrL1+Lqq+C0=
Endpoint = 203.0.113.1:51820
# 仅办公网段、DMZ走VPN流量，不全局代理
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25
