[Interface]
Address = 10.10.10.2/24
PrivateKey = 4P9aY5tlJuAANPwfnVDD2NNFPOXPecARLpe7KiYQlnI=

[Peer]
PublicKey = wP+kEw/HTP3+MC/di4G5vT+inKmu7kVJQbYwTCfGt3g=
Endpoint = 203.0.113.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25