[Interface]
Address = 10.10.10.1/24
PrivateKey = iF8yV/afXqu4yO/D10hST0Ot6PbUoQGe0Iz6wFikY1s=
ListenPort = 51820

[Peer]
PublicKey = 2RYxFzmdX47S0uva+WSGVE+xeCtE3Vsy9xOS6Y5hEw8=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25