[Interface]
Address = 10.10.10.2/24
PrivateKey = cPRGULttZXs3S4huVEnRugA3TwOevrtxBzXc1kkPWE0=

[Peer]
PublicKey = Trjp94f3gyymikFjds5M1KXgU64R/FNAg8iSwzaU9FQ=
Endpoint = 203.0.113.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25
