[Interface]
Address = 10.10.10.1/24
PrivateKey = 2FAe74kVIXzC8iVrFFl8xRUOPqZvKxj1HKjLdaaXNFk=
ListenPort = 51820

[Peer]
PublicKey = 1JqF4yQuNFDioPbUSxVVZkZJE3Nb+j2FPx5ryFO0wkE=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
