# fw防火墙WireGuard服务端配置（文档别名vpn-fw.conf）
[Interface]
Address = 10.10.10.1/24
PrivateKey = EGBfeBRThYc8WT0lSASt7pjcu+drrzYjtfD7ZdxxrkI=
ListenPort = 51820

[Peer]
PublicKey = 8NnZupZ7uMrHmsBTO+bRH7YEj1YdQPcUBmVlt0Z2hFE=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
