[Interface]
Address = 10.10.10.1/24
PrivateKey = mI4xz5Meh+Ejz7HoY8aOSf1lOnUUUrHteEA5i46dkFc=
ListenPort = 51820

[Peer]
PublicKey = kddRl5QXLz4LvcXS+juuMYA4oNo07A2mOFOvtCosQl8=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
