[Interface]
Address = 10.10.10.2/24
PrivateKey = gCDHBVqB+ragEW2l8tp2Th2paDNy22ZxgRNwSlZnU0Q=

[Peer]
PublicKey = 1/TV6GIgK7zDmsHquMz+E/kfx05S9gWQJAkJH5Rhrho=
Endpoint = 192.0.2.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25
