[Interface]
Address = 10.10.10.2/24
PrivateKey = +AJCWERYekNgswI9JdJ109pK1yAOZUWkfcNVOOZCzVA=
[Peer]
PublicKey = NVME1+6wPyfc+bSoP59NF50zkvXBLiCnQiqaO0cqtEY=
Endpoint = 203.0.113.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive =25
