[Interface]
# 远程客户端在隧道内的私有三层通信地址
Address = 192.168.100.2/24

# 客户端生成的私钥（用于证明自身节点身份）
PrivateKey = <远程办公端生成的私钥_REMOTE_PRIVATE_KEY>

[Peer]
# 边界防火墙网关 (FW) 的公钥（用于校验服务端合法性并建立握手）
PublicKey = <边界防火墙网关生成的公钥_FW_PUBLIC_KEY>

# 客户端的物理 Endpoint 指向：跨越 Internet 二层桥接域，锁定防火墙的外部公网 IP 与端口
Endpoint = 198.51.100.1:51820

# 客户端侧路由引流规则：
# 192.168.100.0/24 用于 VPN 内部骨干网通信
# 172.16.10.0/24  使流向企业受信任内网的流量被安全牵引至隧道内
# 172.16.30.0/24  使流向核心业务服务区的流量被安全牵引至隧道内
AllowedIPs = 192.168.100.0/24, 172.16.10.0/24, 172.16.30.0/24

# 状态维持（NAT 穿透维持机制）：每隔 25 秒定时发送有状态心跳包，防止边界有状态防火墙因超时清理连接追踪表导致隧道中断
PersistentKeepalive = 25