[Interface]
Address = 10.10.10.1/24
ListenPort = 51820
PrivateKey = <FW_PRIVATE_KEY>

PostUp = sysctl -w net.ipv4.ip_forward=1
PostDown = sysctl -w net.ipv4.ip_forward=0

[Peer]
PublicKey = <REMOTE_PUBLIC_KEY>
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25