[Interface]
Address = 10.10.10.2/24
PrivateKey = UBqz3pueK08VWbqRNADJvM03mhH/heluceDMHFNCBlk=

[Peer]
PublicKey = aicM5v0FF2Xeq4etqLAC9Hc19dz5aONexblVB0p4oA0=
# 替换为实验fw外网接口IP 203.0.113.1
Endpoint = 203.0.113.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25
