[Interface]
Address = 10.10.10.1/24
PrivateKey = wDAwkQmyll8aL+76hoxRNCcjy+eoC/ygPvMGbkWUx04=
ListenPort = 51820

[Peer]
PublicKey = dgYVhKHev78k4vxxjxNO46JjPVuDtkOjJDHTFGNIylc=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
