[Interface]
Address = 10.10.10.1/24
PrivateKey = qIgWz0PedqP2KRq+ygMFg0Xvez09aHjeiDGmdpcFB1o=
ListenPort = 51820

[Peer]
PublicKey = 4TnJQkyPOCQkJIyDu5t3AUQTATTkvB6Zf4Y2mdeitUI=
AllowedIPs = 10.10.10.2/32
PersistentKeepalive = 25
