[Interface]
Address = 10.10.10.2/24
PrivateKey = MGwmNq1j1Ejba/JqQaIgIIu8EVXxPEB4pHD8jaeR7FQ=

[Peer]
PublicKey = RuJGeFw19oFpGcN19RijFCXgdoAsnn6jwkd+rJI6fRc=
Endpoint = 203.0.113.1:51820
AllowedIPs = 10.20.0.0/24,10.40.0.0/24
PersistentKeepalive = 25
